
export const songListMaster = [
  { title: "100 Years", artist: "Five for Fighting" },
  { title: "3Am", artist: "Matchbox Twenty" },
  { title: "50 Ways To Say Goodbye", artist: "Train" },
  { title: "7 Years", artist: "Lukas Graham" },
  { title: "A Drop In The Ocean", artist: "Ron Pope" },
  { title: "A Sky Full Of Stars", artist: "Coldplay" },
  { title: "A Thousand Years", artist: "Christina Perri" },
  { title: "Aint No Sunshine", artist: "Bill Withers" },
  { title: "All Of Me", artist: "John Legend" },
  { title: "All Star", artist: "Smash Mouth" },
  { title: "All The Small Things", artist: "Blink-182" },
  { title: "All These Things That Ive Done", artist: "The Killers" },
  { title: "Almost Sweet Music", artist: "Hozier" },
  { title: "Alone Together Acoustic", artist: "Fall Out Boy" },
  { title: "Angel Of Small Death And The Codeine Scene", artist: "Hozier" },
  { title: "Angela Acoustic", artist: "The Lumineers" },
  { title: "Arcane - Enemy", artist: "Misc Cartoons" },
  { title: "As The World Caves In", artist: "Matt Maltese" },
  { title: "Awake My Soul", artist: "Mumford & Sons" },
  { title: "Baby Blue Eyes", artist: "A Rocket to the Moon" },
  { title: "Backseat Serenade", artist: "All Time Low" },
  { title: "Bad Blood", artist: "Bastille" },
  { title: "Bad Day", artist: "Daniel Powter" },
  { title: "Bad Habits", artist: "Ed Sheeran" },
  { title: "Bad Liar", artist: "Imagine Dragons" },
  { title: "Barcelona", artist: "George Ezra" },
  { title: "Be Alright", artist: "Dean Lewis" },
  { title: "Beautiful Crazy", artist: "Luke Combs" },
  { title: "Beautiful People", artist: "Ed Sheeran" },
  { title: "Before You Go", artist: "Lewis Capaldi" },
  { title: "Beggin", artist: "Maneskin" },
  { title: "Believer", artist: "Imagine Dragons" },
  { title: "Best Day Of My Life", artist: "American Authors" },
  { title: "Best Part Of Me", artist: "Ed Sheeran" },
  { title: "Billionaire Acoustic", artist: "Travie McCoy" },
  {
    title: "Black Horse And The Cherry Tree",
    artist: "KT Tunstall",
  },
  { title: "Blame", artist: "Bastille" },
  { title: "Blame It On Me", artist: "George Ezra" },
  { title: "Blinding Lights", artist: "The Weeknd" },
  { title: "Bloodstream", artist: "Ed Sheeran" },
  { title: "Boulevard Of Broken Dreams", artist: "Green Day" },
  { title: "Breakeven", artist: "The Script" },
  { title: "Breathe 2 Am", artist: "Anna Nalick" },
  { title: "Brown Eyed Girl", artist: "Van Morrison" },
  { title: "Bruises", artist: "Lewis Capaldi" },
  { title: "Bubbly", artist: "Colbie Caillat" },
  { title: "Budapest", artist: "George Ezra" },
  { title: "Build Me Up Buttercup", artist: "The Foundations" },
  { title: "Californication", artist: "Red Hot Chili Peppers" },
  { title: "Cant Help Falling In Love", artist: "Elvis Presley" },
  { title: "Castle On The Hill", artist: "Ed Sheeran" },
  { title: "Catch And Release", artist: "Matt Simons" },
  { title: "Cecilia And The Satellite", artist: "Andrew McMahon" },
  { title: "Champagne Supernova", artist: "Oasis" },
  { title: "Chasing Cars", artist: "Snow Patrol" },
  { title: "Cherry Wine", artist: "Hozier" },
  { title: "Cigarette Daydreams", artist: "Cage the Elephant" },
  { title: "Cleopatra Acoustic", artist: "The Lumineers" },
  { title: "Clocks", artist: "Coldplay" },
  { title: "Closer", artist: "The Chainsmokers" },
  { title: "Cold Cold Cold", artist: "Cage the Elephant" },
  { title: "Collide", artist: "Howie Day" },
  { title: "Come As You Are Acoustic", artist: "Nirvana" },
  { title: "Come On Get Higher", artist: "Matt Nathanson" },
  { title: "Come Together", artist: "The Beatles" },
  { title: "Cough Syrup", artist: "Young the Giant" },
  { title: "Counting Stars", artist: "OneRepublic" },
  { title: "Cover Me Up", artist: "Morgan Wallen" },
  { title: "Cradles", artist: "Sub Urban" },
  { title: "Crashed Acoustic", artist: "Daughtry" },
  { title: "Crazy", artist: "Gnarls Barkley" },
  { title: "Creep", artist: "Radiohead" },
  { title: "Dance Monkey", artist: "Tones And I" },
  { title: "Dancing On My Own", artist: "Calum Scott" },
  { title: "Daylight", artist: "Maroon 5" },
  {
    title: "Dirty Little Secret Acoustic",
    artist: "The All-American Rejects",
  },
  { title: "Dont", artist: "Ed Sheeran" },
  { title: "Dont Let Me Down", artist: "The Chainsmokers" },
  { title: "Dont Stop Believin", artist: "Journey" },
  { title: "Drops Of Jupiter", artist: "Train" },
  { title: "Drugs", artist: "Tai Verdes" },
  { title: "Easy On Me", artist: "Adele" },
  { title: "Everlong", artist: "Foo Fighters" },
  { title: "Every Breaking Wave", artist: "U2" },
  { title: "Every Storm Runs Out Of Rain", artist: "Gary Allan" },
  { title: "Everybody Talks", artist: "Neon Trees" },
  { title: "Everything", artist: "Michael Buble" },
  { title: "Fall For You", artist: "Secondhand Serenade" },
  { title: "Falling Slowly", artist: "Lee DeWyze" },
  { title: "Far Away", artist: "Nickelback" },
  { title: "Fast Car", artist: "Tracy Chapman" },
  { title: "Feel Good Inc", artist: "Gorillaz" },
  { title: "Favorite Liar", artist: "The Wrecks" },
  { title: "Feel It Still", artist: "Portugal. The Man" },
  { title: "Feeling Good", artist: "Michael Buble" },
  { title: "Feels Like Tonight", artist: "Daughtry" },
  { title: "Fix You", artist: "Coldplay" },
  { title: "Fire And The Flood", artist: "Vance Joy" },
  { title: "Flaws", artist: "Bastille" },
  { title: "Float On", artist: "Modest Mouse" },
  { title: "Fly Away Acoustic", artist: "Lenny Kravitz" },
  { title: "Fly Me To The Moon", artist: "Frank Sinatra" },
  { title: "Folsom Prison Blues", artist: "Johnny Cash" },
  { title: "For The First Time", artist: "The Script" },
  { title: "Georgia", artist: "Vance Joy" },
  { title: "Ghost Of Me", artist: "Daughtry" },
  { title: "Giants", artist: "Dermot Kennedy" },
  { title: "Girls Like You", artist: "Maroon 5" },
  { title: "Gone Gone Gone", artist: "Phillip Phillips" },
  { title: "Grenade", artist: "Bruno Mars" },
  { title: "Half Of My Heart", artist: "John Mayer" },
  { title: "Hallelujah", artist: "Jeff Buckley" },
  { title: "Hallucinogenics", artist: "Matt Maeson" },
  { title: "Happier Than Ever", artist: "Billie Eilish" },
  { title: "Havana", artist: "Camila Cabello" },
  { title: "Havent Met You Yet", artist: "Michael BublÃƒÂ©" },
  { title: "Heartbreak Warfare", artist: "John Mayer" },
  { title: "Hero", artist: "Chad Kroeger" },
  { title: "Hey Soul Sister", artist: "Train" },
  { title: "Hey There Delilah", artist: "Plain White T's" },
  { title: "Ho Hey", artist: "The Lumineers" },
  { title: "Hold Back The River Acoustic", artist: "James Bay" },
  { title: "Home Acoustic", artist: "Daughtry" },
  { title: "Home", artist: "Edward Sharpe and the Magnetic Zeros" },
  { title: "Home", artist: "Phillip Phillips" },
  { title: "Hook", artist: "Blues Traveler" },
  { title: "Hotel California", artist: "Eagles" },
  { title: "House Of The Rising Sun", artist: "The Animals" },
  { title: "How To Save A Life", artist: "The Fray" },
  { title: "How You Remind Me Acoustic", artist: "Nickelback" },
  { title: "Howling For You", artist: "The Black Keys" },
  { title: "Hurt", artist: "Johnny Cash" },
  { title: "I Bet My Life", artist: "Imagine Dragons" },
  { title: "I Fall Apart Acoustic", artist: "Post Malone" },
  { title: "I Feel Like Im Drowning", artist: "Two Feet" },
  { title: "I Just Wanna Run", artist: "The Downtown Fiction" },
  { title: "I Miss You", artist: "Blink-182" },
  { title: "I See Fire", artist: "Ed Sheeran" },
  { title: "I Still Havent Found What Im Looking For", artist: "U2" },
  { title: "I Want It That Way", artist: "Backstreet Boys" },
  {
    title: "I Will Follow You Into The Dark",
    artist: "Death Cab for Cutie",
  },
  { title: "I Will Wait", artist: "Mumford & Sons" },
  { title: "If The World Was Ending", artist: "JP Saxe" },
  { title: "If Today Was Your Last Day", artist: "Nickelback" },
  { title: "If You Only Knew", artist: "Shinedown" },
  { title: "If You Want Love", artist: "NF" },
  { title: "Ily I Love You Baby", artist: "Surf Mesa" },
  { title: "Im A Mess", artist: "Ed Sheeran" },
  { title: "Im Not The Only One", artist: "Sam Smith" },
  { title: "Im Yours", artist: "Jason Mraz" },
  { title: "Into The Night", artist: "Santana" },
  { title: "Iris", artist: "Goo Goo Dolls" },
  { title: "Island In The Sun", artist: "Weezer" },
  { title: "Isnt She Lovely", artist: "Stevie Wonder" },
  { title: "It Will Come Back", artist: "Hozier" },
  { title: "It Will Rain", artist: "Bruno Mars" },
  { title: "Its Not My Time", artist: "3 Doors Down" },
  { title: "Its Not Over", artist: "Daughtry" },
  { title: "Its Time", artist: "Imagine Dragons" },
  { title: "Jamie All Over Acoustic", artist: "Mayday Parade" },
  { title: "Jar Of Hearts", artist: "Christina Perri" },
  { title: "Jumper", artist: "Third Eye Blind" },
  { title: "Just The Two Of Us", artist: "Grover Washington Jr." },
  { title: "Keep The Wolves Away", artist: "Uncle Lucius" },
  { title: "Kiss Me", artist: "Sixpence None the Richer" },
  { title: "Kryptonite", artist: "3 Doors Down" },
  { title: "Lady May", artist: "Tyler Childers" },
  { title: "Landslide", artist: "Fleetwood Mac" },
  { title: "Last Kiss", artist: "Pearl Jam" },
  { title: "Lego House", artist: "Ed Sheeran" },
  { title: "Let Her Go", artist: "Passenger" },
  { title: "Let It Go", artist: "James Bay" },
  { title: "Lethargy", artist: "Bastille" },
  { title: "Life After You", artist: "Daughtry" },
  { title: "Lights Down Low", artist: "MAX (Max Schneider)" },
  { title: "Life Is A Highway", artist: "Rascal Flatts" },
  { title: "Like Im Gonna Lose You", artist: "Meghan Trainor" },
  { title: "Like Real People Do", artist: "Hozier" },
  { title: "Lips Of An Angel", artist: "Hinder" },
  { title: "Little Black Submarines", artist: "The Black Keys" },
  { title: "Little Lion Man", artist: "Mumford & Sons" },
  { title: "Little Talks", artist: "Of Monsters and Men" },
  { title: "Live In The Moment", artist: "Portugal. The Man" },
  { title: "Location", artist: "Khalid" },
  { title: "Locked Out Of Heaven", artist: "Bruno Mars" },
  { title: "Lonely Boy", artist: "The Black Keys" },
  { title: "Lost Boy", artist: "Ruth B." },
  { title: "Love Someone", artist: "Lukas Graham" },
  { title: "Love Yourself", artist: "Justin Bieber" },
  { title: "Lovely", artist: "Billie Eilish" },
  { title: "Loving Is Easy", artist: "Rex Orange County" },
  { title: "Lucky", artist: "Jason Mraz" },
  { title: "Mad World", artist: "Gary Jules" },
  { title: "Make It Rain", artist: "Ed Sheeran" },
  { title: "Mariposa", artist: "Peach Tree Rascals" },
  { title: "Maybe I", artist: "Des Rocs" },
  { title: "Me And My Broken Heart", artist: "Rixton" },
  { title: "Meet Virginia", artist: "Train" },
  { title: "Mess Is Mine", artist: "Vance Joy" },
  { title: "Misery", artist: "Maroon 5" },
  { title: "Mountain Sound", artist: "Of Monsters and Men" },
  { title: "Movement", artist: "Hozier" },
  { title: "Mr Brightside", artist: "The Killers" },
  { title: "Mr Jones", artist: "Counting Crows" },
  { title: "My Body", artist: "Young the Giant" },
  { title: "My Hero Acoustic", artist: "Foo Fighters" },
  { title: "Need You Now", artist: "Lady A (Lady Antebellum)" },
  { title: "Never Say Never", artist: "The Fray" },
  { title: "Night Changes", artist: "One Direction" },
  { title: "Nina", artist: "Ed Sheeran" },
  { title: "No Surprise", artist: "Daughtry" },
  { title: "Nose On The Grindstone", artist: "Tyler Childers" },
  { title: "Nothing", artist: "The Script" },
  { title: "Numb", artist: "Linkin Park" },
  { title: "Ocean Eyes", artist: "Billie Eilish" },
  { title: "On The Inside", artist: "Daughtry" },
  { title: "One More Night", artist: "Maroon 5" },
  { title: "Ophelia", artist: "The Lumineers" },
  { title: "Outnumbered", artist: "Dermot Kennedy" },
  { title: "Over My Head Cable Car", artist: "The Fray" },
  { title: "Payphone Acoustic", artist: "Alex G ((Sandy) Alex G)" },
  { title: "Photograph", artist: "Ed Sheeran" },
  { title: "Pompeii Acoustic", artist: "Bastille" },
  { title: "Pride And Joy", artist: "Stevie Ray Vaughan & Double Trouble" },
  { title: "Pumped Up Kicks", artist: "Foster the People" },
  { title: "Rhythm Of Love", artist: "Plain White T's" },
  { title: "Rivers And Roads", artist: "The Head and the Heart" },
  { title: "Rocket Man", artist: "Elton John" },
  { title: "Rolling In The Deep", artist: "Adele" },
  { title: "Santeria", artist: "Sublime" },
  { title: "Saturday Sun", artist: "Vance Joy" },
  { title: "Say Something", artist: "A Great Big World" },
  { title: "Say You Wont Let Go", artist: "James Arthur" },
  { title: "Second Chance", artist: "Shinedown" },
  { title: "Set Fire To The Rain", artist: "Adele" },
  { title: "Sex And Candy", artist: "Marcy Playground" },
  { title: "Shape Of My Heart", artist: "Sting" },
  { title: "Shivers", artist: "Ed Sheeran" },
  { title: "Shut Up And Dance", artist: "WALK THE MOON" },
  { title: "Sign Of The Times", artist: "Harry Styles" },
  { title: "Simple Man", artist: "Shinedown" },
  { title: "Skinny Love", artist: "Birdy" },
  { title: "Skyfall", artist: "Adele" },
  { title: "Snow Hey Oh", artist: "Red Hot Chili Peppers" },
  { title: "Sober Up", artist: "AJR" },
  { title: "Someone Like You", artist: "Adele" },
  { title: "Something Just Like This", artist: "The Chainsmokers" },
  { title: "Stand By Me", artist: "Ben E. King" },
  { title: "Stay", artist: "Rihanna" },
  { title: "Stay With Me", artist: "Sam Smith" },
  { title: "Stereo Hearts", artist: "Gym Class Heroes" },
  { title: "Stitches", artist: "Shawn Mendes" },
  { title: "Stolen Dance", artist: "Milky Chance" },
  { title: "Stubborn Love", artist: "The Lumineers" },
  { title: "Suit And Jacket", artist: "Judah & The Lion" },
  { title: "Sweater Weather Acoustic", artist: "The Neighbourhood" },
  { title: "Sweet Child O Mine", artist: "Guns N' Roses" },
  { title: "Take Me To Church", artist: "Hozier" },
  { title: "Take It Back", artist: "Ed Sheeran" },
  { title: "Tennessee Whiskey", artist: "Chris Stapleton" },
  { title: "The A Team", artist: "Ed Sheeran" },
  { title: "The Bones", artist: "Maren Morris" },
  { title: "The Cave", artist: "Mumford & Sons" },
  { title: "The Humours Of Whiskey", artist: "Hozier" },
  { title: "The Lazy Song", artist: "Bruno Mars" },
  { title: "The Man Who Cant Be Moved", artist: "The Script" },
  { title: "The Night We Met", artist: "Lord Huron" },
  { title: "The Reason", artist: "Hoobastank" },
  { title: "The Scientist", artist: "Coldplay" },
  { title: "The Seeker", artist: "The Who" },
  { title: "The Sound Of Silence", artist: "Disturbed" },
  { title: "There She Goes", artist: "Sixpence None the Richer" },
  { title: "These Days", artist: "Rascal Flatts" },
  { title: "Thinking Out Loud", artist: "Ed Sheeran" },
  { title: "This Love", artist: "Maroon 5" },
  { title: "This Town", artist: "Niall Horan" },
  { title: "Tighten Up", artist: "The Black Keys" },
  { title: "Titanium", artist: "David Guetta" },
  { title: "To Be Alone", artist: "Hozier" },
  { title: "Too Close", artist: "Alex Clare" },
  { title: "Too Good At Goodbyes", artist: "Sam Smith" },
  { title: "Toxic", artist: "Britney Spears" },
  { title: "Treat You Better", artist: "Shawn Mendes" },
  { title: "Trojans", artist: "Atlas Genius" },
  { title: "Unsteady", artist: "X Ambassadors" },
  { title: "Unwell", artist: "Matchbox Twenty" },
  { title: "Visiting Hours Live", artist: "Ed Sheeran" },
  { title: "Viva La Vida", artist: "Coldplay" },
  { title: "Wake Me Up When September Ends", artist: "Green Day" },
  { title: "Wanted Dead Or Alive", artist: "Bon Jovi" },
  { title: "Warriors", artist: "Imagine Dragons" },
  { title: "Watermelon Sugar", artist: "Harry Styles" },
  { title: "Way Down We Go Live", artist: "Kaleo" },
  { title: "We Are Young", artist: "Fun." },
  {
    title: "Welcome To The Black Parade",
    artist: "My Chemical Romance",
  },
  { title: "West Coast", artist: "Imagine Dragons" },
  { title: "What About Now", artist: "Daughtry" },
  { title: "What I Got", artist: "Sublime" },
  { title: "What Its Like", artist: "Everlast" },
  { title: "What Ive Done", artist: "Linkin Park" },
  { title: "When I Was Your Man", artist: "Bruno Mars" },
  { title: "When The Stars Go Blue", artist: "Ryan Adams" },
  { title: "When We Were Young", artist: "Adele" },
  { title: "When You Were Young", artist: "The Killers" },
  { title: "White House Road", artist: "Tyler Childers" },
  { title: "Wonderwall", artist: "Oasis" },
  { title: "Wont Go Home Without You", artist: "Maroon 5" },
  { title: "Work Song", artist: "Hozier" },
  { title: "Would You Mind", artist: "Friday Pilots Club" },
  { title: "You Are Gold", artist: "The National Parks" },
  { title: "You Found Me", artist: "The Fray" },
  { title: "Your Love", artist: "Daithi De Nogla" },
  { title: "Zombie", artist: "The Cranberries" },
].sort((a, b) => {
  // sort artist
  const artist = a.artist > b.artist ? 1 : b.artist > a.artist ? -1 : 0;
  if (artist !== 0) {
    return artist;
  }

  // sort song
  return a.title > b.title ? 1 : b.title > a.title ? -1 : 0;
});
